In [62]:
import uproot

import numpy as np
import pandas as pd

In [66]:
CSV = "/Users/user/data/research/proton-deuteron/bruno/csv/run.csv"
ANATREE = "/Users/user/data/research/proton-deuteron/bruno/root/MergedAnaTree_Run2_Beam_Pos100A_2022_01.root"
RECO = "/Users/user/data/research/proton-deuteron/recoproton/reco/75235436_47/lariat_digit_r009480_sr0269_20160613T080850_evtsel_1_Reco_20250311T182758.root"
RAW = "/Users/user/data/research/proton-deuteron/rawprotons/proton_extracted_root/extracted_lariat_digit_r009482_sr0270_20160613T083519_evtsel_1.root"

# CSV

In [67]:
csv = pd.read_csv(CSV)

In [65]:
csv.columns

Index(['run', ' subrun', ' event', ' nslice', ' trktype', ' beamline_mass',
       ' wctrkmomentum', ' tof', ' ntrkcalopts', ' trkdedx', ' cke', ' incint',
       ' trklength', ' trkendx', ' trkendy', ' trkendz', ' residualrange',
       ' positio0tpc', ' positionytpc', ' positionztpc', ' decayatrest',
       ' negativeke'],
      dtype='object')

# ANATREE

In [5]:
anatree = uproot.open(ANATREE)
anatree.keys(), anatree.classnames()

(['anatree;1', 'anatree/anatree;883', 'anatree/anatree;882'],
 {'anatree;1': 'TDirectory',
  'anatree/anatree;883': 'TTree',
  'anatree/anatree;882': 'TTree'})

In [6]:
tree = anatree['anatree/anatree']
tree.keys()

['run',
 'subrun',
 'event',
 'evttime',
 'efield',
 'lifetime',
 't0',
 'nclus',
 'clustertwire',
 'clusterttick',
 'cluendwire',
 'cluendtick',
 'cluplane',
 'ntracks_reco',
 'trkvtxx',
 'trkvtxy',
 'trkvtxz',
 'trkendx',
 'trkendy',
 'trkendz',
 'trkstartdcosx',
 'trkstartdcosy',
 'trkstartdcosz',
 'trkenddcosx',
 'trkenddcosy',
 'trkenddcosz',
 'trkWCtoTPCMatch',
 'trklength',
 'trkg4id',
 'primarytrkkey',
 'ntrkcalopts',
 'trkpida',
 'trkke',
 'trkdedx',
 'trkdqdx',
 'trkrr',
 'trkpitch',
 'trkxyz',
 'nhits',
 'hit_plane',
 'hit_wire',
 'hit_channel',
 'hit_peakT',
 'hit_driftT',
 'hit_charge',
 'hit_electrons',
 'hit_ph',
 'hit_rms',
 'hit_g4id',
 'hit_g4frac',
 'hit_g4nelec',
 'hit_g4energy',
 'hit_tstart',
 'hit_tend',
 'hit_trkid',
 'hit_dQds',
 'hit_dEds',
 'hit_ds',
 'hit_resrange',
 'hit_x',
 'hit_y',
 'hit_z',
 'beamline_mass',
 'nwctrks',
 'wctrk_XFaceCoor',
 'wctrk_YFaceCoor',
 'wctrk_theta',
 'wctrk_phi',
 'wctrk_momentum',
 'wctrk_Px',
 'wctrk_Py',
 'wctrk_Pz',
 'wctrk

In [7]:
tree.show()

name                 | typename                 | interpretation                
---------------------+--------------------------+-------------------------------
run                  | int32_t                  | AsDtype('>i4')
subrun               | int32_t                  | AsDtype('>i4')
event                | int32_t                  | AsDtype('>i4')
evttime              | double                   | AsDtype('>f8')
efield               | float                    | AsDtype('>f4')
lifetime             | float                    | AsDtype('>f4')
t0                   | int32_t                  | AsDtype('>i4')
nclus                | int32_t                  | AsDtype('>i4')
clustertwire         | float[]                  | AsJagged(AsDtype('>f4'))
clusterttick         | float[]                  | AsJagged(AsDtype('>f4'))
cluendwire           | float[]                  | AsJagged(AsDtype('>f4'))
cluendtick           | float[]                  | AsJagged(AsDtype('>f4'))
cluplane          

In [8]:
trkvtxz = tree["trkvtxz"]
np.array(trkvtxz)

array([array([3.5821757], dtype=float32),
       array([ 1.9958979, 21.629667 , 52.524895 , 12.953415 , 57.39073  ,
              77.68185  , 74.15722  , 33.68319  , 30.989206 , 43.915573 ,
              64.36788  , 77.58126  , 48.78939  , 28.496572 , 20.359123 ,
              12.487426 , 79.51538  , 54.25654  , 45.3554   , 73.14404  ,
              19.51431  , 44.221092 , 72.864044 ], dtype=float32)        ,
       array([5.032116 , 3.5723794], dtype=float32), ...,
       array([ 3.5649245,  3.877226 ,  3.3830006, 23.726118 ], dtype=float32),
       array([3.212946 , 3.5840027], dtype=float32),
       array([ 3.5172124,  3.40767  , 34.42115  , 21.788465 , 30.733494 ,
              27.39992  , 77.6668   ], dtype=float32)                    ],
      shape=(580638,), dtype=object)

# RECO

In [9]:
reco = uproot.open(RECO)
reco.keys(), reco.classnames()

(['RootFileDB;1',
  'MetaData;1',
  'FileIndex;1',
  'Parentage;1',
  'EventHistory;1',
  'Events;1',
  'EventMetaData;1',
  'SubRuns;1',
  'SubRunMetaData;1',
  'Runs;1',
  'RunMetaData;1',
  'ResultsTree;1',
  'ResultsMetaData;1'],
 {'RootFileDB;1': 'TKey',
  'MetaData;1': 'TTree',
  'FileIndex;1': 'TTree',
  'Parentage;1': 'TTree',
  'EventHistory;1': 'TTree',
  'Events;1': 'TTree',
  'EventMetaData;1': 'TTree',
  'SubRuns;1': 'TTree',
  'SubRunMetaData;1': 'TTree',
  'Runs;1': 'TTree',
  'RunMetaData;1': 'TTree',
  'ResultsTree;1': 'TTree',
  'ResultsMetaData;1': 'TTree'})

In [32]:
metadata = reco["Runs"]
metadata.keys()

['RunAuxiliary',
 'sumdata::RunData_daq__EventBuilderNoMerge.',
 'sumdata::RunData_daq__EventBuilderNoMerge./sumdata::RunData_daq__EventBuilderNoMerge.present',
 'sumdata::RunData_daq__EventBuilderNoMerge./sumdata::RunData_daq__EventBuilderNoMerge.rangeSetID',
 'sumdata::RunData_daq__EventBuilderNoMerge./sumdata::RunData_daq__EventBuilderNoMerge.obj',
 'sumdata::RunData_daq__EventBuilderNoMerge./sumdata::RunData_daq__EventBuilderNoMerge.obj/sumdata::RunData_daq__EventBuilderNoMerge.obj.fDetName']

# RAW

In [34]:
raw = uproot.open(RAW)
raw.keys(), raw.classnames()

(['ana;1', 'ana/raw;1'], {'ana;1': 'TDirectory', 'ana/raw;1': 'TTree'})

In [35]:
tree = raw["ana/raw"]
tree.show()

name                 | typename                 | interpretation                
---------------------+--------------------------+-------------------------------
run                  | int32_t                  | AsDtype('>i4')
subrun               | int32_t                  | AsDtype('>i4')
event                | int32_t                  | AsDtype('>i4')
evttime              | double                   | AsDtype('>f8')
efield               | float                    | AsDtype('>f4')
lifetime             | float                    | AsDtype('>f4')
t0                   | int32_t                  | AsDtype('>i4')
raw_samples          | std::vector<uint64_t>    | AsJagged(AsDtype('>u8'), he...
raw_pedestal         | std::vector<float>       | AsJagged(AsDtype('>f4'), he...
raw_sigma            | std::vector<float>       | AsJagged(AsDtype('>f4'), he...
raw_rawadc           | std::vector<int16_t>     | AsJagged(AsDtype('>i2'), he...
raw_channel          | std::vector<uint32_t>    | AsJagged(

In [58]:
print(tree["raw_rawadc"].array())

[[-1, -1, -1, -1, 0, 0, 0, 0, 0, 1, ..., 0, -1, -1, -1, -1, -1, -1, -1, -1, -1]]
